### ISSUE TITLE
Force layout exceeds call stack size.

### ISSUE THREAD

**Issue by artbeglaryan** [mbostock/d3#2408] opened 2015-04-28 20:44 UTC
Hi. I'm new in d3.js and I'm trying to render a huge graph by using d3.layout.force.

My graph has a more that 5000 nodes and more than 8000 links. Maybe there is a limitation for nodes and links count?

When I render only a nodes, all looks fine(rendered slowly, but it's not a critical)

In url you can find JSON and html
https://drive.google.com/folderview?id=0BzE3fJc8LPFWQS1naGk5OVlfVVU&usp=sharing

**Comment by mbostock** [comment] 2015-10-22 16:22
I expect the issue is that many of the nodes are coincident, causing the quadtree to be degenerate and then causing very deep recursion.

**Comment by mbostock** [comment] 2016-04-26 01:10
This has been fixed in 4.0 thanks to the new non-recursive [d3-quadtree](https://github.com/d3/d3-quadtree) implementation.

**Closed by mbostock** 2016-04-26 01:10 UTC
Labels: bug
