### ISSUE TITLE
Permission Request

### ISSUE THREAD

**Issue by zjqqayuukitan** [mbostock/d3#2743] opened 2016-02-19 08:04 UTC
We would like to use the d3.v3.js on commercial products. but according to our enginering regulation, 'BSD-3-Clause licensed javascript should be include the license description'.
So, your source code does not include it.
Can you please add BSD-3-Clause License to your source code, or comment here for permission?

Thank you for coopration.

**Comment by mbostock** [comment] 2016-02-19 15:31
Duplicate of #2741. The LICENSE is here: https://github.com/mbostock/d3/blob/master/LICENSE

**Closed by mbostock** 2016-02-19 15:31 UTC
