### ISSUE TITLE
Build with almond failing in d3

### ISSUE THREAD

**Issue by egucciar** [mbostock/d3#2642] opened 2015-11-16 15:04 UTC
on this line:

  if (typeof define === "function" && define.amd) define(this.d3 = d3); else if (typeof module === "object" && module.exports) module.exports = d3; else this.d3 = d3;

getting this error from almond:

Uncaught Error: See almond README: incorrect module build, no module name

please advise or fix by adding module name

**Comment by mbostock** [comment] 2015-11-16 15:59
Duplicate of #2617.

**Closed by mbostock** 2015-11-16 15:59 UTC
