### ISSUE TITLE
"Inspect Element" activates drag behavior

### ISSUE THREAD

**Issue by partap** [mbostock/d3#2498] opened 2015-07-21 19:04 UTC
If you have, e.g., a force-directed graph with drag behavior applied, and then right click a node to select "Inspect Element" in the dev tools, the click starts a drag operation on the node, which doesn't end until you click on the SVG element again, at which point it's been moved.  Very frustrating, especially if you need to inspect values when the element is at that particular position.

The problem is that *all* mousedowns start a drag operation...  I couldn't find a way to cancel from an event handler based on the mouse button once started, so I made a small modification in the d3 code:
added an optional `options` argument to `d3.behavior.drag()`, `d3.behavior.zoom()` and `force.layout()`.

The options object can contain a `buttons` array, listing which buttons are valid to trigger a `dragstart` or `zoomstart` event. (0=left, 1=middle, 2=right for right handed mice)

```
force = d3.layout.force(...)
drag = force.drag({buttons: [0, 1]}) // drag nodes with left or middle button only
node = d3.selectAll(...).call(drag)
```

I'm using zoom as well in my app... I decided to use LMB for dragging nodes or panning the entire layout if there's no node under the cursor.  Middle mouse button will always pan, even if clicked on a node:
```
// pan layout with left or middle button.
zoom = d3.behavior.zoom({buttons: [0,1]})
svg = d3.select(...)
  .call(zoom).scaleExtent([0.25, 4.0]).on('zoom', function () {...})

force = d3.layout.force(...)
drag = force.drag({buttons: [0]}) // drag nodes only with left mouse button
node = d3.selectAll(...)
  .call(drag)
  .on('dragstart', function () { d3.event.stopPropagation() }) // prevent layout panning when node is dragged
```

If there is another way to prevent RMB from initiating drags, I'd like to know how.  Otherwise, if this patch looks like it might be useful to anybody else, I can open a PR.

Thanks,
-partap

**Comment by mbostock** [comment] 2015-07-22 21:24
Duplicate of #1627.

**Closed by mbostock** 2015-07-22 21:24 UTC
