### ISSUE TITLE
Object doesn't support property or method 'transition'  in 3.3 

### ISSUE THREAD

**Issue by sherryyur** [mbostock/d3#1491] opened 2013-08-27 05:25 UTC
World Tour Map not working : http://bl.ocks.org/mbostock/4183330

It's working in IE on version 3.2.8. But not in 3.3. Any suggestion to get this working?

SCRIPT438: Object doesn't support property or method 'transition' 
 d3.v3.min.js, line 4 character 29727

**Comment by sorn00** [comment] 2015-01-15 17:00
I am still seeing the Object doesn't support property or method 'transition' d3.js error after installing 3.3.2

**Comment by andresgutgon** [comment] 2015-01-28 10:24
I've been reproducing this bug with `3.5.x`. In IE 9 and IE 10. If I switch to version `3.4.4` the error disapears

**Comment by emepyc** [comment] 2015-02-06 11:06
Yes, I can reproduce this problem (IE9, v3.5.3): Object doesn't support property or method 'transition', d3.js line 8600.

**Comment by jasondavies** [comment] 2015-02-06 15:46
Reproduced.  The problem is that IE9 doesn’t support prototype injection, so we use direct extension instead.  However, this assumes that all methods are already on the prototype object at the time of subclassing, which unfortunately is not the case for `d3_selectionRoot` as it is defined at the end of `selection/selection.js`, which is expanded before `selection/transition.js`.

There is a similar problem for `d3_selectionPrototype.on` and `d3_selectionPrototype.interrupt`, which are declared after `d3_selectionRoot` is defined, if you look at the SMASHed file.

Perhaps `d3.selection` should be modified to use lazy initialisation, rather than eagerly initialising `d3_selectionRoot`.  Patch here: #2223.

**Comment by mbostock** [comment] 2015-02-07 16:25
Fixed in #2225 for 3.5.4.

**Closed by mbostock** 2015-02-07 16:25 UTC
Labels: bug, ms
