### ISSUE TITLE
Column sizing in Gallery is not correct

### ISSUE THREAD

**Issue by zelator29** [mbostock/d3#2718] opened 2016-01-22 16:36 UTC
I am only able to see two columns of the gallery. I see for for a brief moment, but it disappears. I have noticed that I can scroll horizontally to see the elements that are missing.

![d3gallerytwocolsscroll](https://cloud.githubusercontent.com/assets/8196847/12516633/6c55f18e-c0fc-11e5-87d5-75de7d0ac9bc.PNG)

![d3gallerytwocols](https://cloud.githubusercontent.com/assets/8196847/12516541/fe7b91b4-c0fb-11e5-945b-830326720df7.PNG)

**Comment by mbostock** [comment] 2016-01-22 17:15
Duplicate of #2713. Someone probably borked the markdown. I can’t reproduce this locally so I don’t know how to fix it, but anyone can edit the gallery.

**Comment by gordonwoodhull** [comment] 2016-01-22 17:51
Looks like the image size was dropped for a few items, fixed it.

**Comment by mbostock** [comment] 2016-01-22 18:25
Thank you!

**Closed** 2016-01-22 18:25 UTC

**Comment by zelator29** [comment] 2016-01-22 19:03
Thanks!
