### ISSUE TITLE
Treemap don't display single elements with a zero value properly

### ISSUE THREAD

**Issue by romsson** [mbostock/d3#2657] opened 2015-11-25 20:58 UTC
A single element with a zero value (mapped to size) appears as a fairly large rectangle (bottom right on attached screenshot) while it should not be visible at all. See http://bl.ocks.org/romsson/133279a7548a5f4a59c9 (tested with v3.5.9)

This may probably be already part of the [treemap layout rewriting effort](https://github.com/d3/d3-hierarchy/pull/14) but this is a case I haven't see mentioned in the list of tests (mbostock/d3#2419 and mbostock/d3#2419).

<img width="958" alt="screen shot 2015-11-25 at 3 47 06 pm" src="https://cloud.githubusercontent.com/assets/586236/11409127/cdddd65e-938b-11e5-8922-e698adcd3fe3.png">

**Comment by mbostock** [comment] 2015-11-25 21:04
Duplicate of d3/d3-hierarchy#2. The rounding mechanism in 3.x is flawed; it ensures that rounded cells are exactly the same size, but then assigns any unused space to the last cell, even if that cell has zero area. This is fixed in d3/d3-hierarchy#14, although that pull request is not yet finished. (I also plan on supporting tabular input data; see d3/d3-hierarchy#18.)

So, there will be a lot of improvements to this layout in 4.0, but the work isn’t quite done yet. Due to the substantial nature of the rewrite, I’m not planning on back-porting the features to 3.x, though it should be easy for you to pull in just the new [d3-hierarchy](https://github.com/d3/d3-hierarchy) module when it’s released and use that with the rest of 3.x (just replacing the treemap layout).

**Closed by mbostock** 2015-11-25 21:04 UTC
