### ISSUE TITLE
Inconsistent zoom behavior between browsers?

### ISSUE THREAD

**Issue by ghyonimor** [mbostock/d3#2426] opened 2015-05-10 11:06 UTC
Hello, 
First of all - thanks for this awesome library!

In a project we're working on recently, we've encountered a problem with how different browsers handle zoom scale, as the mousewheel delta is not normalized in d3.
As a solution we plan on overriding d3_behavior_zoomWheel.

I'd appreciate your output on this matter.

Thanks in advance.

**Comment by mbostock** [comment] 2015-10-22 04:45
Possibly related #2589.

**Comment by mbostock** [comment] 2015-12-03 17:38
Duplicate of #2589.

**Closed by mbostock** 2015-12-03 17:38 UTC
Labels: bug, ms
