### ISSUE TITLE
d3.scale.log invert should exactly map range endpoints to domain endpoints.

### ISSUE THREAD

**Issue by pallosp** [mbostock/d3#2108] opened 2014-11-10 11:03 UTC
Example (tested in Chrome 39 beta):

```js
d3.scale.log().domain([10, 1000]).range([0, 1]).invert(1) // 999.999999999999
```

It's possible to ensure numerical stability with Math.pow:

```js
function log_scale_invert(value, domain, range) {
  var l = (value - range[0]) / (range[1] - range[0]);
  var sign = domain[0] * domain[1] <= 0 ? NaN : domain[0] > 0 ? 1 : -1;
  return sign * Math.pow(sign * domain[1], l) * Math.pow(sign * domain[0], 1 - l);
}

log_scale_invert(1, [10, 1000], [0, 1]); // 1000
```

**Comment by mbostock** [comment] 2015-10-26 04:18
This will require a fairly substantial change to how the log scale is implemented. The issue is that the log scale composes a linear scale, whose domain is the log-transform of the log scale. So, if you create a log scale with base 10 and a domain of [10, 1000], internally it’s backed by a linear scale with a domain of [1, 2.9999999999999996], the latter being Math.log(1000) / Math.log(10).

On the other hand, the linear scale implementation isn’t that complicated, so just doing a copy-pasta and then customizing it for log scales might be feasible. Or, perhaps there’s a different refactoring to enable the domain to be stored exactly.

**Comment by mbostock** [comment] 2015-10-26 04:25
BTW, this applies to pow scales, too:

```js
d3.scale.sqrt().domain([1, 20]).invert(1) // 20.000000000000004
```

**Comment by mbostock** [comment] 2016-03-01 04:54
This is partly fixed in [d3-scale](https://github.com/d3/d3-scale) for D3 4.0:

```js
d3.scaleLog().domain([10, 1000]).range([0, 1]).invert(1) // 1000
d3.scaleLog().domain([10, 1000]).range([0, 1]).invert(0) // 10
```

However, the sqrt example still fails:

```js
d3.scaleSqrt().domain([1, 20]).invert(1) // 20.000000000000004
```

As I wrote in https://github.com/d3/d3-scale/pull/27#issuecomment-165004151:

> I don’t think there’s a general way to make the pow scale more accurate given that the exponent is arbitrary. There is a way to make the sqrt scale more accurate (see [this implementation](https://gist.github.com/mbostock/3cfa5a25dd80f3b031f2)), but I think it might be reasonable to live with the slight inaccuracy in favor of the general implementation.

**Closed by mbostock** 2016-03-01 04:54 UTC
Labels: bug
