### ISSUE TITLE
Quantize scale produces incorrect result on qunatized range thresholds

### ISSUE THREAD

**Issue by barrybecker4** [mbostock/d3#2513] opened 2015-08-05 18:45 UTC
Suppose I create a quantize scale like this:
var quantizeScale = d3.scale.quantize().domain([4.2, 6.2]).range(d3.range(10));

Then the qunatized bins should be [4.2, 4.4], [4.4, 4.6], [4.6, 4.8], [4.8, 5], [5, 5.2], ... [6, 6.2]

There is a problem getting the correct range value when scaling some of the threshold values.
My expectation is that the low value of each bin (shown above) should be included in the bin, and the high value should be excluded.
This is the case most of the time, but not always. Because of floating point precision issues (like the fact that .3 - .1 is not .2), we sometimes get unexpected results.

For example,
 quantizeScale(4.9999) should be 3 (and is)
 quantizeScale(5) should be 4 (but is 3)
 quantizeScale(5.001) should be 4 (and is)
 
 The inconsistent behavior causes lots of subtle problems.
 I have a proposed fix, but I'm not sure if it is the best fix, or if it works in all cases.
 The fix is in d3's quantize.js
 
 I altered the scale function to be
  function scale(x) {
	 return range[Math.max(0, Math.min(i, Math.floor(Number(kx * (x - x0)).toFixed(12))))];
  }
  
 and the invertExtent function to be
 
 scale.invertExtent = function(y) {
	    y = range.indexOf(y);
	    y = y < 0 ? NaN : y / kx + x0;
	    return [+Number(y).toFixed(12), +Number(y + 1 / kx).toFixed(12)];
 };

This makes sure that numbers like 5.999999999999 or 4.0000000000001 get rounded to something reasonable so that the correct bin is selected when we are on the boundary.

**Comment by tristanreid** [comment] 2015-08-05 20:36
Your math is a little off ((6.4 - 4.2) / 10 == .22, not .2), but that doesn't make your point less clear, I think.

    var q = d3.scale.quantize().domain([4.2, 6.4]).range(d3.range(10))
    q.range().forEach(function(r){ console.log(r + ':' + q.invertExtent(r));});

0:4.2,4.42
1:4.42,4.64
2:4.640000000000001,4.86
3:4.86,5.08
4:5.08,5.3
5:5.300000000000001,5.5200000000000005
6:5.5200000000000005,5.74
7:5.74,5.96
8:5.960000000000001,6.180000000000001
9:6.180000000000001,6.4

**Comment by barrybecker4** [comment] 2015-08-05 21:14
I updated my initial post so that it goes from 4.2 to 6.2. Then the bins are correct. Thanks for adding the clarifying code snippet.  When I change 6.2 to 6.2, you can still see that some of the numbers are off by a little bit (because of IEEE precision issues). Here is what I see:

0:4.2,4.42
1:4.42,4.64
2:4.640000000000001,4.86
3:4.86,5.08
4:5.08,5.3
5:5.300000000000001,5.5200000000000005
6:5.5200000000000005,5.74
7:5.74,5.96
8:5.960000000000001,6.180000000000001
9:6.180000000000001,6.4

The symptom I see in my chart, for which this is the root cause, is that when the user clicks on a bar, then sometimes get two selected.

**Comment by mbostock** [comment] 2015-10-22 06:15
Thanks for filing this interesting bug, and sorry it took me so long to get back to you. (I’ve been on paternity leave.)

There is technically no such thing as 4.2 in IEEE 754. The actual value is closer to 4.20000000000000017763568394002504646778106689453125. So, that quantization threshold is ever so slightly greater than 5; equivalently, when the scale computes the output range index for the input value 5, it computes 5 - 4.20000000000000017763568394002504646778106689453125 = 0.79999999999999982236431605997495353221893310546875. This divided by 2 / 10 = 0.200000000000000011102230246251565404236316680908203125, which gives 3.99999999999999911182158029987476766109466552734375, which is then floored to 3 because it is less than 4.

You could arbitrarily truncate input values and the domain to 12 decimal places, but what if the scale’s domain is intentionally very small? What if your domain represents, say, atom sizes? That doesn’t seem like a general solution and could introduce other unexpected behavior (albeit in less common cases).

My take is that the problem is *not* that quantize is returning the wrong value, but that quantize.invertExtent and quantize are inconsistent. As you say:

> My expectation is that the low value of each bin (shown above) should be included in the bin, and the high value should be excluded.

So, if quantize.invertExtent(3) returns [4.8, 5], then quantize(4.8) should return 3 and quantize(5) should return 4. Instead, quantize(4.8) returns 2 and quantize(5) returns 3. Similarly, quantize.invertExtent(2) returns [4.6000000000000005, 4.800000000000001], so the ranges aren’t aligned due to precision error: quantize.invertExtent(i)[0] should equal quantize.invertExtent(i-1)[1].

I’ve filed d3/d3-scale#17 to track this in 4.0. I’m not sure yet exactly what the fix is, but it should be doable. I don’t plan on fixing this for 3.x—instead for 4.0—so I will be closing this bug. Please followup in the d3-scale repo, if you like.

(Tangentially related d3/d3-arrays#5.)

**Closed by mbostock** 2015-10-22 06:15 UTC
Labels: bug

**Comment by mbostock** [comment] 2015-12-17 00:47
This has been fixed in d3-scale for 4.0; see d3/d3-scale@1b07e7abc38253df4beb35f1d785f42f7e0a8c55. My solution was to compute explicit quantization thresholds and then bisect, like a threshold scale, so that *quantize*.invertExtent(*y*) is guaranteed to be consistent with *quantize*(*x*). I also made the threshold computation slightly more accurate, but it’s still floating point.
