### ISSUE TITLE
When used as AMD still exports global

### ISSUE THREAD

**Issue by danez** [mbostock/d3#2665] opened 2015-12-03 15:13 UTC
Why is d3 still adding the global d3 if used as AMD module?
https://github.com/mbostock/d3/blob/master/src/end.js#L1
In our case this causes a lot of troubles, as we are in the process of migrating a legacy system (which uses no module loader) to a new webpack base solution (with modules).
As both ways seem to write the global variable, d3 gets confused and lots of exceptions happen.

All other packages we use don't do that and properly use `define()` only.

**Comment by mbostock** [comment] 2015-12-03 17:23
Duplicate of #2645. See #1921 and #1693. To summarize: this was done because many D3 plugins assumed the existence of a global `d3`, so when AMD support was added and removed the global, those plugins broke.

The `d3` global will go away in 4.0 when everyone switches to the [D3 module pattern](http://bost.ocks.org/mike/d3-plugin/). This not a backwards-compatible change and thus requires being tied to the next major version.

**Closed by mbostock** 2015-12-03 17:23 UTC

**Comment by danez** [comment] 2015-12-03 18:38
Ahh thanks. Until version 4 gets released, I solved it by telling webpack not set `define` for d3.

```json
loaders: [{
    test: /d3\.js$/,
    loader: "imports?define=>false"
}]
```
