### ISSUE TITLE
`dragend` fires immediately in IE11 with touch

### ISSUE THREAD

**Issue by langdonx** [mbostock/d3#1724] opened 2014-02-04 19:14 UTC
I might be in a Venn diagram intersection of my own, but I've got this Windows 8 laptop that I'm trying to get touch support worked out for.

In Chrome32 and Firefox 26, dragging works with both mouse and touch:

http://jsbin.com/iBuCogIw/18

In IE11 though, when dragging with touch, `dragend` fires immediately.  When dragging with the mouse, it works fine.

That's it, in a nutshell, but to further seclude myself and potentially aid in a fix, dragging with touch works *if* I embed an ActiveX control into the element being dragged.  I'm not entirely sure what including the ActiveX control does to the DIV or the event chain, but for some reason, the `dragmove` event starts firing via touch when it's in there.

http://jsbin.com/eDeWuSAm/1

It's got the Windows Media Player classid in there now, but I'm actually using FBVLC.

Will post more if I can figure anything out.

**Comment by mbostock** [comment] 2015-12-03 17:36
Duplicate of #2556. Proposed fix in #2403.

**Closed by mbostock** 2015-12-03 17:36 UTC
Labels: ms
