### ISSUE TITLE
treemap layout calculation is wrong with padding

### ISSUE THREAD

**Issue by likwifi** [mbostock/d3#2729] opened 2016-02-03 13:52 UTC
please refer to fiddle http://jsfiddle.net/likwifi/Qh9X5/7349/ 
in right bottom corner large box appears
![treemap](https://cloud.githubusercontent.com/assets/1791670/12784072/67a1bf96-ca9e-11e5-9d06-298f48c61a8c.png)
![treemapcorrect](https://cloud.githubusercontent.com/assets/1791670/12784131/cc7b6d9a-ca9e-11e5-8a06-397fe52f7600.png)

**Comment by mitu-lv** [comment] 2016-02-04 15:16
This issue does not appear only with padding enabled.
Here is another example:
http://jsfiddle.net/ep4mg4eL/

**Comment by mbostock** [comment] 2016-02-04 16:35
This is a duplicate issue, which you will find if you search for treemap
issues.

**Comment by mbostock** [comment] 2016-02-04 17:44
Duplicate of #1821. The problem is that the rounding implementation always rounds down to ensure that the cells don’t go outside the box, but then you’re left with some empty space that doesn’t get filled. The new treemap layout implementation in d3-hierarchy will fix this issue, but the implementation is not yet complete. See also d3/d3-hierarchy#2.

**Closed by mbostock** 2016-02-04 17:44 UTC

**Comment by likwifi** [comment] 2016-02-05 06:56
@mbostock if it is possible can you please provide estimate for this.
