### ISSUE TITLE
Warning in Firefox for using __prototype__

### ISSUE THREAD

**Issue by MalteFabian** [mbostock/d3#2179] opened 2015-01-06 11:06 UTC
Everytime d3 gets loaded you can see a waring in the console: "mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create"

This message points to the following lines in d3:

var d3_subclass = {}.__proto__ ? function(object, prototype) {
    object.__proto__ = prototype;
  } : function(object, prototype) {
    for (var property in prototype) object[property] = prototype[property];
  };

I'd consider to change the code in order to get rid of the warning and to update the code (using __protoype__ is deprecated, isn't it?).

**Comment by jasondavies** [comment] 2015-01-06 11:13
Duplicate of #1805.

**Closed by jasondavies** 2015-01-06 11:13 UTC
