### ISSUE TITLE
CSS transform interpolation.

### ISSUE THREAD

**Issue by aeschylus** [mbostock/d3#2507] opened 2015-07-30 02:47 UTC
[Edit. Former title: Transition with 2d CSS (DOM, not SVG) transform does not retrieve correct start value from existing selection.]

Illustrated at this fiddle: http://jsfiddle.net/j2vq6v3q/4/

It's likely I'm just missing something, but I believe the div should transition from its _present position_ to the _updated position_, not pop back to 0,0 first and then transition. What am I doing wrong, or is this a bug?

**Comment by aeschylus** [comment] 2015-07-30 04:54
Found several solutions: http://jsfiddle.net/dgbt6u6p/1/, http://jsfiddle.net/19jaL6bm/3/

It seems d3 will do the interpolation if it is in matrix form, since apparently it translates any 3d transform to that form anyway as part of the canonical representation internally (maybe...?). See: https://d3js.slack.com/archives/feedback-requests/p1438224888000109

**Comment by mbostock** [comment] 2015-10-22 05:12
The problem is that D3 doesn’t understand CSS transforms. So, when you ask it to transition the transform style, it does what it does when transitioning any style, which is to say it retrieves the current computed value of that style and then uses [interpolate](https://github.com/d3/d3-interpolate#interpolate) to tween to the desired value.

The current value of a transform style is always matrix form, as defined by the spec. So you can transition between two matrix form transforms using D3’s default interpolator, but often that’s not what you want. And if you don’t specify the target value in matrix form, then the behavior is essentially undefined. So you will have to use transition.styleTween and specify your own interpolator if you want to transition CSS transforms with D3.

(Or, you can use native CSS transitions, rather than doing it in D3. This is typically more performant, because it eliminates the need for JavaScript to manage the transition. And you can still use D3 to trigger the transition, say by adding or removing a class, or by setting the transform style within the transition start event.)

D3 understands SVG transforms because transition.attr has a special case to detect the "transform" attribute, and then uses [interpolateTransform](https://github.com/d3/d3-interpolate#interpolateTransform). (Arguably, it should only do this on SVG elements, but it’s unlikely that the transform attribute will appear on other elements. I filed d3/d3-transition#13 to track this.)

We could extend D3 to understand CSS transforms, too. But we’d need interpolateTransform to be able to parse CSS transforms (d3/d3-interpolate#6) and then we’d need transition.style to detect when the transform style was being set (presumably only on HTML elements? unclear… d3/d3-transition#12).

I’m closing this because I don’t think we’ll make this change for 3.x, but we might for 4.0. Please followup on the linked issues, if you like.

**Closed by mbostock** 2015-10-22 05:12 UTC
Labels: req
