### ISSUE TITLE
Feature request: Grouping of arcs

### ISSUE THREAD

**Issue by GitNoise** [mbostock/d3#2709] opened 2016-01-12 09:49 UTC
I've been trying to group arcs using d3.svg.arc() with .padAngle() to achive this:

![pie](https://cloud.githubusercontent.com/assets/2017520/12259826/7a5e992a-b918-11e5-98bf-06260040e789.png)

This result does not seem possible with the current implementation of .padAngle(). 

An extension would be to add a gap after an arc instead of adding padding on both sides of it. The extension would also recalculate the area of the arcs so that the proportion between the arcs is preserved.

I would love to work on this but I need some pointers on how I could go about recalculating the proportions after a gap has been inserted.

**Comment by mbostock** [comment] 2016-01-12 22:31
Duplicate of #2237; see d3/d3-shape#42 for a possible fix.

**Closed by mbostock** 2016-01-12 22:31 UTC
